CREATE DATABASE ecommerce_hybrid;
use ecommerce_hybrid;

CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    phone VARCHAR(20),
    registration_date DATE NOT NULL,
    city VARCHAR(80),
    country VARCHAR(80) NOT NULL DEFAULT 'Germany'
);

CREATE TABLE categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

ALTER TABLE categories
MODIFY category_id INT NOT NULL AUTO_INCREMENT;

DROP TABLE IF EXISTS product_reference;

CREATE TABLE product_reference (
    product_id INT NOT NULL,
    category_id INT NOT NULL,
    sku VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (product_id),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
);


DESCRIBE customers;



CREATE TABLE orders (
    order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
    total_amount DECIMAL(12,2) NOT NULL,

    PRIMARY KEY (order_id),

    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT chk_order_total
        CHECK (total_amount >= 0),

    CONSTRAINT chk_order_status
        CHECK (
            order_status IN (
                'Pending',
                'Processing',
                'Shipped',
                'Delivered',
                'Cancelled'
            )
        )
);

CREATE TABLE order_items (
    order_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,

    PRIMARY KEY (order_item_id),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_item_price
        CHECK (unit_price >= 0)
);


CREATE TABLE payments (
    payment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'Pending',
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount DECIMAL(12,2) NOT NULL,

    PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_payment_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payment_method
        CHECK (
            payment_method IN (
                'Credit Card',
                'Debit Card',
                'PayPal',
                'Bank Transfer'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'Pending',
                'Completed',
                'Failed',
                'Refunded'
            )
        )
);

CREATE TABLE inventory (
    inventory_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    product_id BIGINT UNSIGNED NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    reorder_level INT NOT NULL DEFAULT 10,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (inventory_id),

    CONSTRAINT uq_inventory_product
        UNIQUE (product_id),

    CONSTRAINT chk_inventory_stock
        CHECK (stock_quantity >= 0),

    CONSTRAINT chk_inventory_reorder
        CHECK (reorder_level >= 0)
);

INSERT INTO categories
(category_name, description)
SELECT
    CONCAT('Category ', n),
    CONCAT('E-commerce product category number ', n)
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO categories
(category_name, description)
SELECT
    CONCAT('Category ', n),
    CONCAT('E-commerce product category number ', n)
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO customers
(
    first_name,
    last_name,
    email,
    phone,
    registration_date,
    city,
    country
)
SELECT
    CONCAT('Customer', n),
    CONCAT('User', n),
    CONCAT('customer', n, '@example.com'),
    CONCAT('+491500', LPAD(n, 5, '0')),
    DATE_SUB(CURRENT_DATE(), INTERVAL (n MOD 365) DAY),
    CASE (n MOD 10)
        WHEN 0 THEN 'Berlin'
        WHEN 1 THEN 'Hamburg'
        WHEN 2 THEN 'Munich'
        WHEN 3 THEN 'Cologne'
        WHEN 4 THEN 'Frankfurt'
        WHEN 5 THEN 'Stuttgart'
        WHEN 6 THEN 'Dusseldorf'
        WHEN 7 THEN 'Leipzig'
        WHEN 8 THEN 'Dresden'
        ELSE 'Bremen'
    END,
    'Germany'
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO product_reference
(
    product_id,
    category_id,
    sku,
    active
)
SELECT
    1000 + n,
    n,
    CONCAT('SKU-', 1000 + n),
    TRUE
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO inventory
(
    product_id,
    stock_quantity,
    reorder_level
)
SELECT
    1000 + n,
    20 + ((n * 17) MOD 180),
    10 + (n MOD 20)
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO orders
(
    customer_id,
    order_date,
    order_status,
    total_amount
)
SELECT
    ((n - 1) MOD 100) + 1,
    DATE_SUB(
        CURRENT_TIMESTAMP(),
        INTERVAL (n MOD 365) DAY
    ),
    CASE (n MOD 5)
        WHEN 0 THEN 'Pending'
        WHEN 1 THEN 'Processing'
        WHEN 2 THEN 'Shipped'
        WHEN 3 THEN 'Delivered'
        ELSE 'Cancelled'
    END,
    50.00 + ((n * 37) MOD 750)
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100
) AS numbers;

INSERT INTO order_items
(
    order_id,
    product_id,
    quantity,
    unit_price
)
SELECT
    ((n - 1) MOD 100) + 1,
    1001 + ((n - 1) MOD 100),
    1 + (n MOD 4),
    25.00 + ((n * 19) MOD 300)
FROM (
    SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
    SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
    SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
    SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
    SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
    SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL
    SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL
    SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL
    SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
    SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL
    SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL
    SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL
    SELECT 49 UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL
    SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
    SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL
    SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60 UNION ALL
    SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL
    SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL
    SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
    SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL
    SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL
    SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL
    SELECT 79 UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL
    SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL
    SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL
    SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90 UNION ALL
    SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL
    SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL
    SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL
    SELECT 100 UNION ALL SELECT 101 UNION ALL SELECT 102 UNION ALL
    SELECT 103 UNION ALL SELECT 104 UNION ALL SELECT 105 UNION ALL
    SELECT 106 UNION ALL SELECT 107 UNION ALL SELECT 108 UNION ALL
    SELECT 109 UNION ALL SELECT 110 UNION ALL SELECT 111 UNION ALL
    SELECT 112 UNION ALL SELECT 113 UNION ALL SELECT 114 UNION ALL
    SELECT 115 UNION ALL SELECT 116 UNION ALL SELECT 117 UNION ALL
    SELECT 118 UNION ALL SELECT 119 UNION ALL SELECT 120 UNION ALL
    SELECT 121 UNION ALL SELECT 122 UNION ALL SELECT 123 UNION ALL
    SELECT 124 UNION ALL SELECT 125 UNION ALL SELECT 126 UNION ALL
    SELECT 127 UNION ALL SELECT 128 UNION ALL SELECT 129 UNION ALL
    SELECT 130 UNION ALL SELECT 131 UNION ALL SELECT 132 UNION ALL
    SELECT 133 UNION ALL SELECT 134 UNION ALL SELECT 135 UNION ALL
    SELECT 136 UNION ALL SELECT 137 UNION ALL SELECT 138 UNION ALL
    SELECT 139 UNION ALL SELECT 140 UNION ALL SELECT 141 UNION ALL
    SELECT 142 UNION ALL SELECT 143 UNION ALL SELECT 144 UNION ALL
    SELECT 145 UNION ALL SELECT 146 UNION ALL SELECT 147 UNION ALL
    SELECT 148 UNION ALL SELECT 149 UNION ALL SELECT 150 UNION ALL
    SELECT 151 UNION ALL SELECT 152 UNION ALL SELECT 153 UNION ALL
    SELECT 154 UNION ALL SELECT 155 UNION ALL SELECT 156 UNION ALL
    SELECT 157 UNION ALL SELECT 158 UNION ALL SELECT 159 UNION ALL
    SELECT 160 UNION ALL SELECT 161 UNION ALL SELECT 162 UNION ALL
    SELECT 163 UNION ALL SELECT 164 UNION ALL SELECT 165 UNION ALL
    SELECT 166 UNION ALL SELECT 167 UNION ALL SELECT 168 UNION ALL
    SELECT 169 UNION ALL SELECT 170 UNION ALL SELECT 171 UNION ALL
    SELECT 172 UNION ALL SELECT 173 UNION ALL SELECT 174 UNION ALL
    SELECT 175 UNION ALL SELECT 176 UNION ALL SELECT 177 UNION ALL
    SELECT 178 UNION ALL SELECT 179 UNION ALL SELECT 180 UNION ALL
    SELECT 181 UNION ALL SELECT 182 UNION ALL SELECT 183 UNION ALL
    SELECT 184 UNION ALL SELECT 185 UNION ALL SELECT 186 UNION ALL
    SELECT 187 UNION ALL SELECT 188 UNION ALL SELECT 189 UNION ALL
    SELECT 190 UNION ALL SELECT 191 UNION ALL SELECT 192 UNION ALL
    SELECT 193 UNION ALL SELECT 194 UNION ALL SELECT 195 UNION ALL
    SELECT 196 UNION ALL SELECT 197 UNION ALL SELECT 198 UNION ALL
    SELECT 199 UNION ALL SELECT 200
) AS numbers;

INSERT INTO payments
(
    order_id,
    payment_method,
    payment_status,
    payment_date,
    amount
)
SELECT
    order_id,
    CASE (order_id MOD 4)
        WHEN 0 THEN 'Credit Card'
        WHEN 1 THEN 'Debit Card'
        WHEN 2 THEN 'PayPal'
        ELSE 'Bank Transfer'
    END,
    CASE (order_id MOD 10)
        WHEN 0 THEN 'Pending'
        WHEN 1 THEN 'Failed'
        WHEN 2 THEN 'Refunded'
        ELSE 'Completed'
    END,
    DATE_ADD(order_date, INTERVAL 1 HOUR),
    total_amount
FROM orders;

SELECT 'categories' AS table_name, COUNT(*) AS record_count
FROM categories

UNION ALL

SELECT 'customers', COUNT(*)
FROM customers

UNION ALL

SELECT 'product_reference', COUNT(*)
FROM product_reference

UNION ALL

SELECT 'inventory', COUNT(*)
FROM inventory

UNION ALL

SELECT 'orders', COUNT(*)
FROM orders

UNION ALL

SELECT 'order_items', COUNT(*)
FROM order_items

UNION ALL

SELECT 'payments', COUNT(*)
FROM payments;

-- query 1

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_status,
    o.total_amount
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
LIMIT 20;

-- query 2
SELECT
    o.order_id,
    o.total_amount,
    oi.product_id,
    oi.quantity,
    oi.unit_price
FROM orders o
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
LIMIT 20;

-- query 3
SELECT
    o.order_id,
    o.total_amount,
    p.payment_method,
    p.payment_status,
    p.amount
FROM orders o
INNER JOIN payments p
    ON o.order_id = p.order_id
LIMIT 20;


